#!/bin/bash
# Deploy ezlocalai - Local AI Inference Server
# Clones ezlocalai, creates a Python venv, installs it, configures env vars, and starts the server.
set -e

INSTALL_DIR="${EZLOCALAI_INSTALL_DIR:-/opt/ezlocalai}"
DEFAULT_MODEL="${EZLOCALAI_DEFAULT_MODEL:-unsloth/Qwen3.5-4B-GGUF}"
LLM_MAX_TOKENS="${EZLOCALAI_MAX_TOKENS:-40000}"
EZLOCALAI_PORT="${EZLOCALAI_PORT:-8091}"
EZLOCALAI_API_KEY="${EZLOCALAI_API_KEY:-}"
WHISPER_MODEL="${EZLOCALAI_WHISPER_MODEL:-large-v3}"
IMG_MODEL="${EZLOCALAI_IMG_MODEL:-Tongyi-MAI/Z-Image-Turbo}"
TTS_ENABLED="${EZLOCALAI_TTS_ENABLED:-true}"
STT_ENABLED="${EZLOCALAI_STT_ENABLED:-true}"
QUANT_TYPE="${EZLOCALAI_QUANT_TYPE:-Q4_K_XL}"
LLM_BATCH_SIZE="${EZLOCALAI_BATCH_SIZE:-2048}"
PYTHON_VERSION="${PYTHON_VERSION:-3.11}"
REPO_URL="https://github.com/DevXT-LLC/ezlocalai.git"

echo "============================================="
echo "  ezlocalai Deployment Script"
echo "============================================="
echo ""
echo "Install directory: ${INSTALL_DIR}"
echo "Default model:     ${DEFAULT_MODEL}"
echo "Max tokens:        ${LLM_MAX_TOKENS}"
echo "Port:              ${EZLOCALAI_PORT}"
echo ""

# ------------------------------------------------------------------
# 1. Ensure Python is available
# ------------------------------------------------------------------
PYTHON_CMD=""
for candidate in "python${PYTHON_VERSION}" "python3" "python"; do
    if command -v "$candidate" &>/dev/null; then
        PYTHON_CMD="$candidate"
        break
    fi
done

if [ -z "$PYTHON_CMD" ]; then
    echo "ERROR: Python not found. Please install Python ${PYTHON_VERSION}+ first."
    echo "You can use the 'install-python' deployment script."
    exit 1
fi

PYTHON_VER=$("$PYTHON_CMD" --version 2>&1 | awk '{print $2}')
echo "Using Python: ${PYTHON_CMD} (${PYTHON_VER})"

# Ensure python3-venv package is available on Debian/Ubuntu
if command -v apt-get &>/dev/null; then
    if ! "$PYTHON_CMD" -m venv --help &>/dev/null 2>&1; then
        echo "Installing python3-venv package..."
        sudo apt-get update -qq
        sudo apt-get install -y "python${PYTHON_VERSION}-venv" 2>/dev/null || \
            sudo apt-get install -y python3-venv 2>/dev/null || true
    fi
fi

# ------------------------------------------------------------------
# 2. Ensure git is available
# ------------------------------------------------------------------
if ! command -v git &>/dev/null; then
    echo "ERROR: git is not installed. Please install git first."
    echo "You can use the 'install-git' deployment script."
    exit 1
fi

# ------------------------------------------------------------------
# 3. Clone or update the repository
# ------------------------------------------------------------------
if [ -d "${INSTALL_DIR}/.git" ]; then
    echo "Updating existing ezlocalai installation..."
    cd "${INSTALL_DIR}"
    git pull --ff-only || {
        echo "WARNING: git pull failed, continuing with existing code."
    }
else
    echo "Cloning ezlocalai repository..."
    sudo mkdir -p "$(dirname "${INSTALL_DIR}")"
    sudo chown "$(whoami)" "$(dirname "${INSTALL_DIR}")" 2>/dev/null || true
    git clone "${REPO_URL}" "${INSTALL_DIR}"
    cd "${INSTALL_DIR}"
fi

# ------------------------------------------------------------------
# 4. Create / update virtual environment
# ------------------------------------------------------------------
VENV_DIR="${INSTALL_DIR}/.venv"
if [ ! -d "${VENV_DIR}" ]; then
    echo "Creating virtual environment..."
    "$PYTHON_CMD" -m venv "${VENV_DIR}"
fi

# Activate venv
source "${VENV_DIR}/bin/activate"
echo "Virtual environment active: ${VENV_DIR}"

# Upgrade pip
pip install --upgrade pip -q

# ------------------------------------------------------------------
# 5. Install ezlocalai in editable mode
# ------------------------------------------------------------------
echo "Installing ezlocalai..."
cd "${INSTALL_DIR}"
pip install -e . -q

# ------------------------------------------------------------------
# 6. Write environment configuration
# ------------------------------------------------------------------
ENV_FILE="${INSTALL_DIR}/.env"
echo "Writing environment configuration to ${ENV_FILE}..."

cat > "${ENV_FILE}" <<ENVEOF
# ezlocalai configuration - generated by deployment script
DEFAULT_MODEL=${DEFAULT_MODEL}
LLM_MAX_TOKENS=${LLM_MAX_TOKENS}
EZLOCALAI_URL=http://0.0.0.0:${EZLOCALAI_PORT}
EZLOCALAI_API_KEY=${EZLOCALAI_API_KEY}
WHISPER_MODEL=${WHISPER_MODEL}
IMG_MODEL=${IMG_MODEL}
TTS_ENABLED=${TTS_ENABLED}
STT_ENABLED=${STT_ENABLED}
QUANT_TYPE=${QUANT_TYPE}
LLM_BATCH_SIZE=${LLM_BATCH_SIZE}
ENVEOF

echo "Configuration written."

# ------------------------------------------------------------------
# 7. Create management wrapper scripts
# ------------------------------------------------------------------
SCRIPTS_DIR="${INSTALL_DIR}/scripts"
mkdir -p "${SCRIPTS_DIR}"

cat > "${SCRIPTS_DIR}/start.sh" <<'STARTEOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"
cd "${SCRIPT_DIR}"
ezlocalai start "$@"
STARTEOF
chmod +x "${SCRIPTS_DIR}/start.sh"

cat > "${SCRIPTS_DIR}/stop.sh" <<'STOPEOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"
cd "${SCRIPT_DIR}"
ezlocalai stop
STOPEOF
chmod +x "${SCRIPTS_DIR}/stop.sh"

cat > "${SCRIPTS_DIR}/restart.sh" <<'RESTARTEOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"
cd "${SCRIPT_DIR}"
ezlocalai restart "$@"
RESTARTEOF
chmod +x "${SCRIPTS_DIR}/restart.sh"

cat > "${SCRIPTS_DIR}/status.sh" <<'STATUSEOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"
cd "${SCRIPT_DIR}"
ezlocalai status
STATUSEOF
chmod +x "${SCRIPTS_DIR}/status.sh"

cat > "${SCRIPTS_DIR}/logs.sh" <<'LOGSEOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${SCRIPT_DIR}/.venv/bin/activate"
cd "${SCRIPT_DIR}"
ezlocalai logs -f
LOGSEOF
chmod +x "${SCRIPTS_DIR}/logs.sh"

echo ""
echo "============================================="
echo "  ezlocalai Deployment Complete!"
echo "============================================="
echo ""
echo "Installation directory: ${INSTALL_DIR}"
echo "Virtual environment:    ${VENV_DIR}"
echo "Configuration file:     ${ENV_FILE}"
echo ""
echo "Management commands (activate venv first):"
echo "  source ${VENV_DIR}/bin/activate"
echo "  ezlocalai start        # Start the server"
echo "  ezlocalai stop         # Stop the server"
echo "  ezlocalai restart      # Restart the server"
echo "  ezlocalai status       # Check server status"
echo "  ezlocalai logs -f      # Follow server logs"
echo ""
echo "Or use the wrapper scripts:"
echo "  ${SCRIPTS_DIR}/start.sh"
echo "  ${SCRIPTS_DIR}/stop.sh"
echo "  ${SCRIPTS_DIR}/restart.sh"
echo "  ${SCRIPTS_DIR}/status.sh"
echo "  ${SCRIPTS_DIR}/logs.sh"
echo ""
LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || ip route get 1 2>/dev/null | awk '{print $7; exit}' || echo "localhost")
echo "Server will be available at: http://${LOCAL_IP}:${EZLOCALAI_PORT}"

# ------------------------------------------------------------------
# 8. Start the server
# ------------------------------------------------------------------
echo ""
echo "Starting ezlocalai..."
cd "${INSTALL_DIR}"
ezlocalai start --model "${DEFAULT_MODEL}"
